elevation_mapping:
  ros__parameters:
    inputs: ["zed2"] # A name to identify the input source

    zed2:
      type: pointcloud # Supported types: pointcloud
      topic: /jetson/zed/point_cloud/cloud_registered
      queue_size: 1
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: perfect
        ignore_points_above: 1.0
        ignore_points_below: -1.0
    map_frame_id: "odom"
    robot_base_frame_id: "base_link" # When testing only the ZED camera use "zed_camera_link" instead.
    robot_pose_with_covariance_topic: "" # Leaving this empty skipps pose covariance updates.
    robot_pose_cache_size: 200
    track_point_frame_id: "zed_camera_link"
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: 0.0
