gridmap_feature_extractor_node:
  ros__parameters:
    elevation_map_topic: "/elevation_map"
    ellipse_a: 0.8
    ellipse_b: 0.05

# latent_feature_extractor_node:
#   ros__parameters:
#     model_path: "$(find-pkg-share soislip_demo)/models/latent_feature_model.onnx"
#     input_topic: "/gridmap"
#     latent_dim: 32

robot_experience_collector_node:
  ros__parameters:
    wheel_separation: 0.512
    robot_frame: "base_link"
    wheel_odom: "odom"
    wheel_odom_source: "frame"
    reference_odom: "map" # when changing this, make sure to also change the map_frame_id in the elevation mapping config file.
    reference_odom_source: "frame"
    sample_distance: 0.2
    min_distance_threshold: 0.05
    min_velocity_threshold: 0.2 
    max_velocity_threshold: 2.0
    odom_timeout_sec: 0.5

soinn_training_node:
  ros__parameters:
    model_path: "/workspaces/vscode_ros2_workspace/src/soinn_slip_learner/soislip_demo/models/soinn_model.pkl"
    init_new_model: true
    sample_topic: "/experience_samples"
    auto_save_period_sec: 20.0

soinn_prediction_node:
  ros__parameters:
    model_path: "/workspaces/vscode_ros2_workspace/src/soinn_slip_learner/soislip_demo/models/soinn_model.pkl"
    model_reload_period_sec: 20.0

slip_prediction_manager:
  ros__parameters:
    elevation_map_topic: "/elevation_map"
    prediction_period_sec: 5.0
