import numpy as np

class ColorUtils: # Or integrate into your SoinnPlus class

    @staticmethod
    def _int_to_base_string_fixed_len(n, base, min_length):
        """
        Converts an integer n to its string representation in a given base,
        padded with leading zeros if necessary to meet min_length.
        This mimics MATLAB's dec2base(N, BASE, L) behavior where L is min_length.
        Note: MATLAB's dec2base for L (min_length): "If the string representation 
        of N in base BASE has fewer than L characters, D is padded with leading zeros. 
        If it has L or more characters, D has the minimum number of characters needed 
        to represent N (that is, D has more than L characters)."
        """
        if not isinstance(base, int) or not (2 <= base <= 36):
            # np.base_repr supports bases from 2 to 36.
            raise ValueError("Base must be an integer between 2 and 36.")
        
        # np.base_repr uses lowercase 'a'-'z' for digits > 9.
        # MATLAB's dec2base uses uppercase 'A'-'Z'.
        s = np.base_repr(n, base=base).upper()
        
        if len(s) < min_length:
            padding = min_length - len(s)
            return ('0' * padding) + s
        return s

    @staticmethod
    def _str_to_num_array(s_digits):
        """
        Converts a string of base digits (e.g., "01A" for base 11) 
        into a NumPy array of corresponding numerical values (e.g., [0, 1, 10]).
        Assumes s_digits contains characters '0'-'9' and 'A'-'Z'.
        """
        num_array = []
        for char_digit in s_digits:
            if '0' <= char_digit <= '9':
                num_array.append(int(char_digit))
            else:  # 'A' through 'Z'
                # ord('A') is 65. 'A' represents 10, 'B' is 11, ...
                num_array.append(ord(char_digit) - ord('A') + 10)
        # Ensure float type for division later
        return np.array(num_array, dtype=float)

    def get_rgb_vectors(self, num_colors_needed):
        """
        Generates a specified number of unique RGB color vectors, normalized to [0,1].
        
        Parameters:
        ----------
        num_colors_needed : int
            The desired number of unique RGB color vectors.

        Returns:
        -------
        np.ndarray
            A NumPy array of shape (num_colors_needed, 3) containing RGB vectors,
            or fewer rows if not enough unique colors could be generated by the
            algorithm's limits and padding is not applied (current version pads).
        """
        if not isinstance(num_colors_needed, int) or num_colors_needed < 0:
            raise ValueError("num_colors_needed must be a non-negative integer.")

        if num_colors_needed == 0:
            return np.empty((0, 3), dtype=float)

        # List to store unique RGB vectors (as NumPy arrays)
        unique_rgbs_list = []
        # Set to store tuples of RGB vectors for efficient uniqueness checking
        unique_rgbs_set = set()

        # MATLAB: maxBase = ceil(power(num, 1/3));
        # This determines how many different 'bases' to iterate through.
        # The loop for 'base' in MATLAB is `for base = 2:maxBase`.
        # We ensure our loop limit for 'base' starts at 2.
        max_base_calc = int(np.ceil(num_colors_needed**(1/3.0)))
        
        # Ensures the loop for 'base_val' runs at least for base_val = 2
        # (which generates 2^3=8 candidate colors before uniqueness).
        max_base_loop_limit = max(2, max_base_calc)

        # MATLAB: for base = 2:maxBase
        for base_val in range(2, max_base_loop_limit + 1):
            # MATLAB: candi = zeros(base^3, 3); (implicitly handled by generating one by one)
            
            # MATLAB: for i = 0:base^3-1
            for i in range(base_val**3):
                # MATLAB: candi(i+1,:) = obj.str2numArry(dec2base(i,base,3));
                # The '3' means 3 "digits" for R, G, B components.
                base_str_repr = ColorUtils._int_to_base_string_fixed_len(i, base_val, 3)
                numeric_repr_vec = ColorUtils._str_to_num_array(base_str_repr)

                # MATLAB: candi = candi / (base-1);
                # Normalization to [0,1] range.
                # (base_val - 1) is safe as base_val starts at 2.
                normalized_color_vec = numeric_repr_vec / (base_val - 1.0)
                
                # Ensure values are clipped if any rounding error occurs, though division should be fine.
                # normalized_color_vec = np.clip(normalized_color_vec, 0.0, 1.0)


                # Uniqueness check and addition logic from MATLAB:
                # tf = true; ... if all(candi(i,:) == rgbs(k,:)) ...
                # if tf, rgbs = cat(1, rgbs, candi(i, :));
                # Using a set of tuples is more Pythonic and efficient for uniqueness.
                color_tuple = tuple(normalized_color_vec) 
                if color_tuple not in unique_rgbs_set:
                    unique_rgbs_set.add(color_tuple)
                    unique_rgbs_list.append(normalized_color_vec) # Store the NumPy array

        # Convert the list of 1D arrays to a 2D NumPy array
        if not unique_rgbs_list:
            # This case should ideally not be hit if num_colors_needed > 0,
            # as base_val=2 should generate at least one color ([0,0,0]).
            final_rgbs_array = np.empty((0, 3), dtype=float)
        else:
            final_rgbs_array = np.array(unique_rgbs_list)

        # MATLAB: rgbs = rgbs(1:num, :);
        # This takes the first 'num' colors found. If fewer than 'num' were found,
        # MATLAB's slicing would error. Here, we provide a more robust handling.
        current_num_found = final_rgbs_array.shape[0]

        if current_num_found >= num_colors_needed:
            return final_rgbs_array[:num_colors_needed, :]
        else:
            # Fewer unique colors were generated than requested with the derived max_base.
            # Pad with a default color (e.g., black) to meet the requested shape.
            # print(f"Warning: Requested {num_colors_needed} colors, but only {current_num_found} "
            #       f"unique colors were generated. Padding remaining with black.")
            padded_rgbs = np.zeros((num_colors_needed, 3), dtype=float)
            if current_num_found > 0: # If some colors were found, fill them in
                padded_rgbs[:current_num_found, :] = final_rgbs_array
            return padded_rgbs